config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :projects do
    collection do
      get :dashboard
      post :kick_start
    end
    resources :records do
      collection do
        post 'open'
      end
      member do
        post 'close'
      end
    end
  end
  get 'records' => 'records#list'
  get 'evaluation' => 'records#evaluate'
  resources :users, only: [:edit, :update]

  root 'projects#dashboard'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  belongs_to :parent, class_name: 'Project'
  has_many :children, class_name: 'Project', foreign_key: 'parent_id', dependent: :destroy
  has_many :records, dependent: :destroy

  attr_accessor :depth, :is_first_child, :is_last_child

  validates :name, presence: true, allow_blank: false
  validates_each :parent_id do |record, attr, value|
    used_ids = []
    current = record
    while current
      if used_ids.include?(current.id)
        record.errors.add(attr, 'It\'s a project tree, not a project cycle!')
        break
      end
      used_ids << current.id
      current = current.parent
    end
  end

  def to_label
    "--" * (depth || 0) + name
  end

  def self.tree projects
    # create the tree
    recursive_tree_worker projects.sort { |a, b| a.name <=> b.name}, 0
  end

  def self.recursive_tree_worker projects, my_depth, my_current_id = nil
    temp_list = []

    # crawl through all projects
    projects.each do |project|
      if project.parent_id == my_current_id
        project.depth = my_depth
        temp_list << project
        temp_list.concat recursive_tree_worker( projects, my_depth + 1, project.id )
      end
    end

    # Add first child and last_child
    unless temp_list.length == 0
      temp_list.first.is_first_child = true
      temp_list.reverse.each do |project|
        if project.depth == my_depth
          project.is_last_child = true
          break
        end
      end
    end

    # return list
    temp_list
  end

  def <=> other
    name <=> other.name
  end
end

__END__
  def <=> other
    if parent_id && other.parent_id && parent_id == other.parent_id
      name <=> other.name
    elsif parent_id && other.parent_id
      parent <=> other.parent
    elsif parent_id == other.id
      1
    elsif parent_id
      parent <=> other
    elsif other.parent_id
      self <=> other.parent
    else
      name <=> other.name
    end
  end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.tree(current_user.projects)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @records = @project.records.order('begun_at DESC').paginate(page: params[:page])
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
    @projects = Project.tree(current_user.projects.reject {|p| p == @project})
  end

  # GET /projects/1/edit
  def edit
    @projects = Project.tree(current_user.projects.reject {|p| p == @project})
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: _('Project was successfully created.') }
        format.json { render :show, status: :created, location: @project }
      else
        @projects = Project.tree(current_user.projects.reject {|p| p == @project})
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: _('Project was successfully updated.') }
        format.json { render :show, status: :ok, location: @project }
      else
        @projects = Project.tree(current_user.projects.reject {|p| p == @project})
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: _('Project was successfully destroyed.') }
      format.json { head :no_content }
    end
  end

  def kick_start
    @project = current_user.projects.build(project_params)
    @project.color = RGB::Color.from_rgb((rand * 256).to_i, (rand * 256).to_i, (rand * 256).to_i).to_rgb_hex
    @project.active = true

    unless @project.save
      format.html { redirect_to dashboard_projects_path, alert: _('Could not create project.') }
      format.json { render json: @project.errors, status: :unprocessable_entity }
      return
    end

    Record.close_last_record_for(current_user.id)
    @record = @project.records.build
    @record.user = current_user
    @record.begun_at = Time.now
    @record.save!

    respond_to do |format|
      if @record.save
        format.html { redirect_to dashboard_projects_path }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { redirect_to dashboard_projects_path, alert: _('Could not create new record.') }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def dashboard
    @open_record = current_user.open_record
    @projects = Project.tree(current_user.projects)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :color, :parent_id, :active)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= semantic_form_for @project do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :parent, collection: @projects
    = f.input :name, label: _('Name')
    = f.input :color, label: _('Colour'), hint: _('Format: #89abcd')
    = f.input :active, label: _('Show in dashboard')
  = f.actions do
    = f.action :submit, as: :button, label: _('Save'), button_html: { class: 'btn btn-primary' }
    = f.action :cancel, as: :link, label: _('Cancel'), button_html: { class: 'btn btn-default' }

app/views/projects/dashboard.html.haml
- if @open_record
  .alert.alert-info{role: 'alert'}
    = form_tag close_project_record_path(@open_record.project, @open_record), method: :post do
      = _('%{ago} ago you started working on %{project}.') % { ago: time_ago_in_words(@open_record.begun_at), project: @open_record.project.name }
      = button_tag _('I\'m done'), class: 'btn btn-primary'

.row
  - @projects.select{ |p| p.active }.each do |project|
    .col-md-2.col-sm3.col-xs-6
      = form_tag open_project_records_path(project), method: :post do
        = button_tag class: 'btn magic-button', style: "background-color:#{project.color};color:#{magic_font_color(project.color)}" do
          = project.name
      %br
  .col-md-2.col-sm3.col-xs-6
    = form_tag kick_start_projects_path(), method: :post, class: 'kick-start-form' do
      = text_field_tag 'project[name]', '', class: 'form-control'
      = select_tag 'project[parent_id]', options_from_collection_for_select(@projects, "id", "to_label"), include_blank: true, class: 'form-control'
      = submit_tag _('Kick-start'), class: 'btn btn-default'
    %br

app/views/projects/edit.html.haml
.page-header
  %h1= _('Edit project')

= render 'form'

app/views/projects/index.html.haml
.page-header
  %h1= _('Projects')

%table.table.table-striped
  %thead
    %tr
      %th= _('Name')
      %th= _('On dashboard')
      %th &nbsp;
  %tbody
    - @projects.each do |project|
      %tr
        %td{style: "border-left:7px solid #{project.color};padding-left:#{8 + project.depth * 20}px;"}= link_to project.name, project
        %td= project.active ? _('Yes') : _('No')
        %td
          = link_to edit_project_path(project) do
            = fa_icon 'edit'

%p
  = link_to new_project_path do
    = fa_icon 'plus'
    = _('Add project')

app/views/projects/new.html.haml
.page-header
  %h1= _('Add project')

= render 'form'

app/views/projects/show.html.haml
.page-header
  %h1= @project.name

= will_paginate @records

%table.table.table-striped
  %thead
    %tr
      %th= _('Begin')
      %th= _('End')
      %th= _('Duration')
      %th &nbsp;
  %tbody
    - @records.each do |record|
      %tr
        %td= time_start record.begun_at
        %td= time_end record.ended_at
        %td= time_diff(record.begun_at, record.ended_at)
        %td
          = link_to edit_project_record_path(@project, record) do
            = fa_icon 'edit'
          = fa_icon 'fw'
          = link_to project_record_path(@project, record), method: :delete, data: { confirm: _('Are you sure?') } do
            = fa_icon 'times'

%p
  = link_to new_project_record_path(@project) do
    = fa_icon 'plus'
    = _('Add record')