config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :projects do
    collection do
      get :dashboard
      post :kick_start
    end
    resources :records do
      collection do
        post 'open'
      end
      member do
        post 'close'
      end
    end
  end
  get 'records' => 'records#list'
  get 'evaluation' => 'records#evaluate'
  resources :users, only: [:edit, :update]

  root 'projects#dashboard'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= _('Tiny Time Tracker')
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  %body
    - if current_user
      .navbar.navbar-default.navbar-static-top
        .container
          %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand(href="#{dashboard_projects_path}") T³
          .navbar-collapse.collapse.navbar-responsive-collapse
            %ul.nav.navbar-nav
              %li= link_to _('Dashboard'), dashboard_projects_path
              %li= link_to _('Projects'), projects_path
              %li= link_to _('Records'), records_path
              %li= link_to _('Evaluation'), evaluation_path
              %li= link_to _('Change Password'), edit_user_path(:current)
              %li= link_to _('Logout'), session_path(:current), method: :delete

    .container
      = bootstrap_flash
      = yield